export { REGISTER_USER, LOGIN_USER, GET_USER } from './userGQL';
export { DELETE_COMMENT, CREATE_COMMENT } from './commentGQL';
export {
  GET_PROJECT,
  GET_PROJECTS,
  CREATE_PROJECT,
  ADD_MEMBER,
} from './project';
export {
  GET_POST,
  GET_POSTS,
  CREATE_POST,
  DELETE_POST,
  LIKE_POST,
  CREATE_PROJECT_POST,
  UPLOAD_FILE,
  GET_PROJECT_POSTS,
} from './postGQL';
