export { REGISTER_USER, LOGIN_USER, GET_USER, GET_FRIENDS } from './userGQL';
export { DELETE_COMMENT, CREATE_COMMENT } from './commentGQL';
export {
  GET_PROJECT,
  GET_PROJECTS,
  CREATE_PROJECT,
  ADD_MEMBER,
  GET_USER_PROJECTS,
  GET_MEMBERS,
} from './projectGQL';
export {
  GET_POST,
  GET_POSTS,
  CREATE_POST,
  DELETE_POST,
  LIKE_POST,
  CREATE_PROJECT_POST,
  UPLOAD_FILE,
  GET_PROJECT_POSTS,
} from './postGQL';
